# Generated by Django 4.2.28 on 2026-02-27 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "submission_type",
                    models.CharField(
                        choices=[
                            ("certificate", "Certificate"),
                            ("cgpa", "CGPA"),
                            ("paper", "Paper"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("file_url", models.FileField(upload_to="submissions/%Y/%m/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "submissions",
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="submissions_user_id_9864cd_idx"
                    ),
                    models.Index(
                        fields=["event"], name="submissions_event_i_fdf5f6_idx"
                    ),
                ],
            },
        ),
    ]
