# Generated by Django 4.2.28 on 2026-02-27 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="submission",
            name="submissions_event_i_fdf5f6_idx",
        ),
        migrations.AlterField(
            model_name="submission",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submissions",
                to="events.event",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="file_url",
            field=models.TextField(),
        ),
    ]
