# Generated by Django 4.2.28 on 2026-02-27 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("submissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, default="")),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "db_table": "admin_reviews",
                "indexes": [
                    models.Index(
                        fields=["decision"], name="admin_revie_decisio_8ed441_idx"
                    ),
                    models.Index(
                        fields=["submission"], name="admin_revie_submiss_9ef3e8_idx"
                    ),
                ],
            },
        ),
    ]
