# Generated by Django 4.2.28 on 2026-02-28 09:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="redemption",
            new_name="shop_redemp_user_id_86280d_idx",
            old_name="shop_redemptions_user_idx",
        ),
        migrations.RenameIndex(
            model_name="redemption",
            new_name="shop_redemp_item_id_aa485f_idx",
            old_name="shop_redemptions_item_idx",
        ),
        migrations.RenameIndex(
            model_name="shopitem",
            new_name="shop_items_is_acti_2591f6_idx",
            old_name="shop_items_is_active_idx",
        ),
        migrations.RenameIndex(
            model_name="shopitem",
            new_name="shop_items_categor_dfef97_idx",
            old_name="shop_items_category_idx",
        ),
    ]
