# Generated by Django 4.2.28 on 2026-02-27 21:09

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("academic", "Academic"),
                            ("cocurricular", "Co-curricular"),
                            ("extracurricular", "Extra-curricular"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("organized_by", models.TextField()),
                ("date", models.DateField(db_index=True)),
                ("location", models.TextField()),
                ("points_per_participant", models.IntegerField()),
                ("winner_points", models.IntegerField()),
                (
                    "winners_roll_nos",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=20),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "events",
                "indexes": [
                    models.Index(fields=["date"], name="events_date_e70fc0_idx"),
                    models.Index(fields=["type"], name="events_type_671f92_idx"),
                ],
            },
        ),
    ]
