# Generated by Django 4.2.28 on 2026-02-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="banner_url",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
