# Generated by Django 4.2.28 on 2026-02-27 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PointLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("credit", "Credit"), ("debit", "Debit")],
                        max_length=10,
                    ),
                ),
                ("points", models.IntegerField()),
                ("reason", models.TextField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("attendance", "Attendance"),
                            ("winner", "Winner"),
                            ("certificate", "Certificate"),
                            ("cgpa", "CGPA"),
                            ("paper", "Paper"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "point_ledger",
                "indexes": [
                    models.Index(
                        fields=["user"], name="point_ledge_user_id_663a0c_idx"
                    ),
                    models.Index(
                        fields=["event"], name="point_ledge_event_i_8489e5_idx"
                    ),
                    models.Index(
                        fields=["source"], name="point_ledge_source_918a06_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("attendance", "Attendance"),
                            ("submission", "Submission"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "participations",
                "indexes": [
                    models.Index(
                        fields=["user"], name="participati_user_id_e62d48_idx"
                    ),
                    models.Index(
                        fields=["event"], name="participati_event_i_bc4841_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="participation",
            constraint=models.UniqueConstraint(
                fields=("user", "event", "source"),
                name="uniq_participation_user_event_source",
            ),
        ),
    ]
