# Generated by Django 4.2.28 on 2026-02-27 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
        ("points", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="participation",
            name="uniq_participation_user_event_source",
        ),
        migrations.AlterField(
            model_name="participation",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="participations",
                to="events.event",
            ),
        ),
        migrations.AlterField(
            model_name="pointledger",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ledger_entries",
                to="events.event",
            ),
        ),
    ]
