# Generated by Django 4.2.28 on 2026-02-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "points",
            "0002_remove_participation_uniq_participation_user_event_source_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pointledger",
            name="source",
            field=models.CharField(
                choices=[
                    ("attendance", "Attendance"),
                    ("winner", "Winner"),
                    ("certificate", "Certificate"),
                    ("cgpa", "CGPA"),
                    ("paper", "Paper"),
                    ("redemption", "Shop Redemption"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
